# Generated by Django 4.2.6 on 2023-10-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_type', models.CharField(max_length=100)),
                ('listing_type', models.CharField(max_length=10)),
                ('bedrooms', models.PositiveIntegerField()),
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
