# Generated by Django 4.2.6 on 2023-10-16 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='bedrooms',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estate',
            name='listing_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='estate',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='estate',
            name='property_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Farm House', 'Farm House'), ('Home', 'Home'), ('Commercial', 'Commercial'), ('Villa', 'Villa'), ('Cottage', 'Cottage'), ('Other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='estate',
            name='title',
            field=models.CharField(max_length=175),
        ),
    ]
